name: Build

on:
  release:
    types: [created]

jobs:

  build:
    runs-on: ubuntu-latest

    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        # token: ${{ secrets.GITHUB_TOKEN }}

    - name: Install Bun
      shell: bash
      run: |
        curl -fsSL https://bun.sh/install | bash
        echo "$HOME/.bun/bin" >> $GITHUB_PATH

    - name: Build minified version
      run: |
        bun build --minify tool.ts --outfile minified/tool-${{ github.ref_name }}-min.js

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: tool-minified
        path: minified/tool-${{ github.ref_name }}-min.js

    - name: Commit Minified Version
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git checkout main
        git add minified/tool-${{ github.ref_name }}-min.js
        git commit -m "Add minified version: tool-${{ github.ref_name }}-min.js"
        git push
