name: Build

on:
  release:
    types: [created]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Bun
      uses: ./.github/workflows/setup-bun.yml

    - name: Build minified version
      run: |
        bun build --minify tool.ts --outfile minified/tool-${{ github.ref_name }}-min.js

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: tool-minified
        path: minified/tool-${{ github.ref_name }}-min.js

    - name: Commit minified version
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add minified/tool-${{ github.ref_name }}-min.js
        git commit -m "Add minified version: tool-${{ github.ref_name }}-min.js"
        git push
